[2022-08-10 23:45:19.316] [renderer1] [critical] Extension 'ms-python.python CANNOT USE these API proposals 'quickPickSortByLabel, testObserver'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-08-10 23:45:19.317] [renderer1] [critical] Extension 'ms-toolsai.jupyter CANNOT USE these API proposals 'notebookControllerKind, notebookWorkspaceEdit, notebookDebugOptions, notebookDeprecated, notebookMessaging, notebookMime, notebookCellExecutionState, portsAttributes, quickPickSortByLabel, notebookKernelSource, interactiveWindow'. You MUST start in extension development mode or use the --enable-proposed-api command line flag
[2022-08-10 23:45:19.447] [renderer1] [error] [ms-toolsai.jupyter]: notebook/kernelSource is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["notebookKernelSource"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
[2022-08-10 23:45:20.640] [renderer1] [error] [Extension Host] globalMsCrypto undefined undefined {"subtle":{},"asn1":{},"url":null,"version":"1.6.5"}
[2022-08-10 23:45:21.212] [renderer1] [error] [Extension Host] extension activation failed Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
    at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:83:68123)
    at d.onDidChangeNotebookCellExecutionState (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:106:52770)
    at new f (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:2:308606)
    at Object.t.resolveInstance (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1395108)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1397046
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1395964
    at Array.map (<anonymous>)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1395936
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1394882)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1397046
    at Object.t.resolve (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1397309)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1380722
    at e._get (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1380488)
    at e.get (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1379131)
    at a.get (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:48723)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:2933890
[2022-08-10 23:45:22.186] [renderer1] [error] Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter: Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookCellExecutionState.
Its package.json#enabledApiProposals-property declares:  but NOT notebookCellExecutionState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
    at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:83:68123)
    at d.onDidChangeNotebookCellExecutionState (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:106:52770)
    at new f (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:2:308606)
    at Object.t.resolveInstance (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1395108)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1397046
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1395964
    at Array.map (<anonymous>)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1395936
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1394882)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1397046
    at Object.t.resolve (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1397309)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1380722
    at e._get (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1380488)
    at e.get (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:1379131)
    at a.get (/home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:48723)
    at /home/manu320/.vscode-oss/extensions/ms-toolsai.jupyter-2022.8.1002170547/out/extension.node.js:17:2933890
[2022-08-10 23:45:22.619] [renderer1] [error] Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python: Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
    at g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:83:68123)
    at Object.get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:106:34047)
    at P.activate (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:745691)
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2251
    at Array.map (<anonymous>)
    at f.activateWorkspace (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2241)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-08-10 23:46:20.210] [renderer1] [error] Git error
[2022-08-10 23:46:21.533] [renderer1] [error] Git error
[2022-08-10 23:46:36.131] [renderer1] [error] Git error
[2022-08-10 23:46:54.721] [renderer1] [error] Git error
[2022-08-10 23:46:55.873] [renderer1] [error] Git error
[2022-08-10 23:47:09.498] [renderer1] [error] Git error
[2022-08-10 23:47:33.011] [renderer1] [error] Git error
[2022-08-10 23:47:48.700] [renderer1] [error] AttributeError: 'HoverDisable' object has no attribute 'namespace_': Error: AttributeError: 'HoverDisable' object has no attribute 'namespace_'
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2147823
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148117
    at Immediate.<anonymous> (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148479)
    at processImmediate (node:internal/timers:464:21)
[2022-08-11 00:00:28.501] [renderer1] [error] ValueError: `column` parameter (1) is not in a valid range (0-0) for line 152 ('\n').: Error: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 152 ('\n').
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2147823
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148117
    at Immediate.<anonymous> (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148479)
    at processImmediate (node:internal/timers:464:21)
[2022-08-11 00:03:03.554] [renderer1] [error] Git error
[2022-08-11 00:04:26.367] [renderer1] [error] ValueError: `column` parameter (1) is not in a valid range (0-0) for line 38 ('').: Error: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 38 ('').
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2147823
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148117
    at Immediate.<anonymous> (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148479)
    at processImmediate (node:internal/timers:464:21)
[2022-08-11 00:04:27.055] [renderer1] [error] Git error
[2022-08-11 00:05:58.838] [renderer1] [error] Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/M9iS.py': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/M9iS.py'
    at l (/usr/lib/code/out/vs/code/electron-main/main.js:30:4146)
    at r.toFileSystemProviderError (/usr/lib/code/out/vs/code/electron-main/main.js:33:42520)
    at r.doCloneFile (/usr/lib/code/out/vs/code/electron-main/main.js:33:41769)
[2022-08-11 00:06:08.241] [renderer1] [error] [File Watcher (parcel)] Unexpected error: basic_string::_M_create (EUNKNOWN) (path: /home/manu320/.config)
[2022-08-11 00:06:08.241] [renderer1] [error] [File Watcher (universal)] restarting watcher after error: basic_string::_M_create
[2022-08-11 00:11:40.499] [renderer1] [error] ValueError: `column` parameter (1) is not in a valid range (0-0) for line 3 ('\n').: Error: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 3 ('\n').
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2147823
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148117
    at Immediate.<anonymous> (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148479)
    at processImmediate (node:internal/timers:464:21)
[2022-08-11 00:11:41.540] [renderer1] [error] ValueError: `column` parameter (1) is not in a valid range (0-0) for line 15 ('\n').: Error: ValueError: `column` parameter (1) is not in a valid range (0-0) for line 15 ('\n').
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2147823
    at /home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148117
    at Immediate.<anonymous> (/home/manu320/.vscode-oss/extensions/ms-python.python-2022.12.0/out/client/extension.js:2:2148479)
    at processImmediate (node:internal/timers:464:21)
[2022-08-11 00:24:58.066] [renderer1] [error] Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/065r.py': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/065r.py'
    at l (/usr/lib/code/out/vs/code/electron-main/main.js:30:4146)
    at r.toFileSystemProviderError (/usr/lib/code/out/vs/code/electron-main/main.js:33:42520)
    at r.doCloneFile (/usr/lib/code/out/vs/code/electron-main/main.js:33:41769)
[2022-08-11 00:25:25.610] [renderer1] [error] Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/gO5d.py': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/gO5d.py'
    at l (/usr/lib/code/out/vs/code/electron-main/main.js:30:4146)
    at r.toFileSystemProviderError (/usr/lib/code/out/vs/code/electron-main/main.js:33:42520)
    at r.doCloneFile (/usr/lib/code/out/vs/code/electron-main/main.js:33:41769)
[2022-08-11 00:25:29.534] [renderer1] [error] Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/UFSd.py': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, copyfile '/home/manu320/.config/backup/qtile/modules/groups.py' -> '/home/manu320/.config/Code - OSS/User/History/254badcc/UFSd.py'
    at l (/usr/lib/code/out/vs/code/electron-main/main.js:30:4146)
    at r.toFileSystemProviderError (/usr/lib/code/out/vs/code/electron-main/main.js:33:42520)
    at r.doCloneFile (/usr/lib/code/out/vs/code/electron-main/main.js:33:41769)
